DCMAW-17101: add step to check if PR title includes apostrophe (#931)
Co-authored-by: James Mooney <178897394+jmooney-dd@users.noreply.github.com>

diff --git a/.github/workflows/job_ci-checks.yml b/.github/workflows/job_ci-checks.yml
--- a/.github/workflows/job_ci-checks.yml
+++ b/.github/workflows/job_ci-checks.yml
@@ -48,6 +48,19 @@ jobs:
         with:
           submodules: true
 
+      - name : Check If PR Title Includes Apostrophe
+        env:
+          TITLE: ${{ github.event.pull_request.title }}
+          REGEX_PATTERN: ^[^']*$
+        run: |
+          echo $TITLE
+          if [[ $TITLE =~ $REGEX_PATTERN ]]; then
+            echo 'PR title is valid'
+          else
+            echo 'PR title includes apostrophe. This causes SAM upload to fail. Remove apostrophe from PR title and retry.'
+            exit 1
+          fi
+
       - name: Setup nodeJS
         uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
         with:
