DCMAW-12245: github action versioning spike

diff --git a/.github/workflows/test-resources-post-merge.yml b/.github/workflows/test-resources-post-merge.yml
--- a/.github/workflows/test-resources-post-merge.yml
+++ b/.github/workflows/test-resources-post-merge.yml
@@ -1,92 +1,133 @@
-name: Test Resources Post Merge
+name: GitHub Jobs Post Merge
+
 on:
   push:
     branches:
       - main
     paths:
-      - "test-resources/**"
-      - ".github/workflows/job_push-docker-image.yml"
-      - ".github/workflows/job_upload-sam-artifact.yml"
-      - ".github/workflows/test-resources-post-merge.yml"
-      - "!test-resources/**/*.md"
-      - "!test-resources/**/*.png"
+      - ".github/jobs/**"
   workflow_dispatch:
 
 permissions:
-  contents: read
+  contents: write
   id-token: write
 
-defaults:
-  run:
-    shell: bash
-    working-directory: ./test-resources
-
 jobs:
-  ci-checks:
-    name: Pre-deployment
-    uses:
-      ./.github/workflows/job_ci-checks.yml
-    with:
-      WORKING_DIRECTORY: test-resources
+  get-file-names:
+    name: Get Names of Files Changed
+    runs-on: ubuntu-24.04
+    env:
+      SAM_CLI_TELEMETRY: 0
+    defaults:
+      run:
+        shell: bash
+        working-directory: .
+    outputs:
+      FILE_NAMES: ${{ steps.get-files.outputs.NAMES }}
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          submodules: true
+          fetch-depth: 0
 
-  run-test-suite:
-    name: Pre-deployment
-    needs: ci-checks
-    uses:
-      ./.github/workflows/job_test-suite.yml
-    with:
-      SONARQUBE_CONTINUE_ON_ERROR: true
-      WORKING_DIRECTORY: test-resources
-    secrets: inherit
+# This is ugly but can't get anything else to work
+      - name: Get File Names
+        id: get-files
+        run: |
+          files=$( git diff origin/main --name-only -- ./.github/jobs )
 
-  push-docker-image-dev:
-    name: Dev
-    needs: 
-      - ci-checks
-      - run-test-suite
-    uses:
-      ./.github/workflows/job_push-docker-image.yml
-    with:
-      WORKING_DIRECTORY: test-resources
-    secrets:
-      CONTAINER_SIGN_KMS_KEY: ${{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
-      GH_ACTIONS_ROLE_ARN: ${{ secrets.TEST_RESOURCES_DEV_GH_ACTIONS_ROLE_ARN }}
-      TEST_IMAGE_REPOSITORY_URI: ${{ secrets.TEST_RESOURCES_DEV_TEST_IMAGE_REPOSITORY_URI }}
+          JSON="["
+          for file in ${files[@]}; do
+              echo $file
+              JSONline="\"$file\","
+              if [[ "$JSON" != *"$JSONline"* ]]; then
+                  JSON="$JSON$JSONline"
+              fi
+          done
 
-  upload-sam-artifact-dev:
-    name: Dev
-    needs: push-docker-image-dev
-    uses:
-      ./.github/workflows/job_upload-sam-artifact.yml
-    with:
-      WORKING_DIRECTORY: test-resources
-    secrets:
-      ARTIFACT_BUCKET: ${{ secrets.TEST_RESOURCES_DEV_ARTIFACT_BUCKET }}
-      GH_ACTIONS_ROLE_ARN: ${{ secrets.TEST_RESOURCES_DEV_GH_ACTIONS_ROLE_ARN }}
-      SIGNING_PROFILE_NAME: ${{ secrets.DEV_SIGNING_PROFILE_NAME }}
+          if [[ $JSON == *, ]]; then
+              JSON="${JSON%?}"
+          fi
+          JSON="$JSON]"
 
-  push-docker-image-build:
-    name: Build
-    needs: 
-      - ci-checks
-      - run-test-suite
-    uses:
-      ./.github/workflows/job_push-docker-image.yml
-    with:
-      WORKING_DIRECTORY: test-resources
-    secrets:
-      CONTAINER_SIGN_KMS_KEY: ${{ secrets.BUILD_CONTAINER_SIGN_KMS_KEY }}
-      GH_ACTIONS_ROLE_ARN: ${{ secrets.TEST_RESOURCES_BUILD_GH_ACTIONS_ROLE_ARN }}
-      TEST_IMAGE_REPOSITORY_URI: ${{ secrets.TEST_RESOURCES_BUILD_TEST_IMAGE_REPOSITORY_URI }}
+          echo $JSON
+          echo "NAMES=$( echo "$JSON" )" >> $GITHUB_OUTPUT
 
-  upload-sam-artifact-build:
-    name: Build
-    needs: push-docker-image-build
-    uses:
-      ./.github/workflows/job_upload-sam-artifact.yml
-    with:
-      WORKING_DIRECTORY: test-resources
-    secrets:
-      ARTIFACT_BUCKET: ${{ secrets.TEST_RESOURCES_BUILD_ARTIFACT_BUCKET }}
-      GH_ACTIONS_ROLE_ARN: ${{ secrets.TEST_RESOURCES_BUILD_GH_ACTIONS_ROLE_ARN }}
-      SIGNING_PROFILE_NAME: ${{ secrets.BUILD_SIGNING_PROFILE_NAME }}
+  create-tags:
+    name: Validate Versions and Create Tags
+    runs-on: ubuntu-24.04
+    needs: get-file-names
+    strategy:
+      matrix:
+        file_name:  ${{ fromJSON(needs.get-file-names.outputs.FILE_NAMES) }}
+    env:
+      SAM_CLI_TELEMETRY: 0
+      FILE_NAME: ${{ matrix.file_name }}
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    defaults:
+      run:
+        shell: bash
+        working-directory: jobs
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          submodules: true
+          fetch-depth: 0
+
+      - name: Setup NodeJS
+        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
+        with:
+          cache: npm
+          cache-dependency-path: jobs/package-lock.json
+          node-version-file: jobs/.nvmrc
+
+      - name: Install Dependencies
+        run: |
+          npm clean-install
+
+      - name: Validate Job Name
+        id: job-name
+        run: |
+          name=$( yq .name ../$FILE_NAME )
+
+          if [[ "$name" =~ ^[a-z0-9-]+$ ]]; then
+            echo "Valid job name."
+            echo "NAME=$name" >> $GITHUB_OUTPUT
+          else
+            echo "Invalid job name."
+            exit 1
+          fi
+
+      - name: Get Version
+        id: get-version
+        run: |
+          version=$( yq .description ../$FILE_NAME | jq .version | tr -d '"' )
+          echo "VERSION=$version" >> $GITHUB_OUTPUT
+
+      - name: Validate Version
+        run: |
+          npm run validate-version $FILE_NAME
+
+      - name: Get Message
+        id: get-message
+        run: |
+          message=$( yq .description ../$FILE_NAME | jq .message )
+          echo "MESSAGE=$message" >> $GITHUB_OUTPUT
+
+      - name: Create and Push Tag
+        run: |
+          job_name=${{ steps.job-name.outputs.NAME }}
+          new_version=${{ steps.get-version.outputs.VERSION }}
+          
+          git tag $job_name/$new_version
+          git push origin $job_name/$new_version
+
+      - name: Create GitHub Release
+        run: |
+          job_name=${{ steps.job-name.outputs.NAME }}
+          message=${{ steps.get-message.outputs.MESSAGE }}
+          new_version=${{ steps.get-version.outputs.VERSION }}
+
+          gh release create $job_name/$new_version ../$FILE_NAME --latest=false --notes "$message"
